// SHOWING PRODUCT  
export const SHOW_PRODUCTS = 'SHOW_PRODUCTS';


// SINGLE PRODUCT TO CART
export const SINGLE_PRODUCT = 'SINGLE_PRODUCT';


// CART TYPES
export const ADDING_TO_CART = "ADDING_TO_CART";
export const REMOVE_ITEM = 'REMOVE_ITEM';